fix: migrate cicd from yarn to pnpm

diff --git a/.github/workflows/frontend-test.yml b/.github/workflows/frontend-test.yml
--- a/.github/workflows/frontend-test.yml
+++ b/.github/workflows/frontend-test.yml
@@ -25,16 +25,16 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node-version }}
-      - name: Check if Yarn is installed
-        id: check_yarn
+      - name: Check if pnpm is installed
+        id: check_pnpm
         run: |
-          if ! command -v yarn &> /dev/null; then
-            echo "Yarn not found, installing..."
-            npm install -g yarn
+          if ! command -v pnpm &> /dev/null; then
+            echo "pnpm not found, installing..."
+            npm install -g pnpm
           else
-            echo "Yarn is already installed."
+            echo "pnpm is already installed."
           fi
       - name: Install dependencies
-        run: yarn install --frozen-lockfile
-      - name: Run Jest
-        run: yarn test --ci
+        run: pnpm install --frozen-lockfile
+      - name: Run Vitest
+        run: pnpm test --ci
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -42,12 +42,12 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
 
-      - name: Install Yarn
+      - name: Install pnpm
         run: |
-          npm install --global yarn || { echo "Yarn installation failed"; exit 1; }
+          npm install --global pnpm || { echo "pnpm installation failed"; exit 1; }
 
       - name: Install frontend dependencies
-        run: yarn install --frozen-lockfile
+        run: pnpm install --frozen-lockfile
 
       - name: Bump version and create tag
         id: bump_version
